---
title: "Awards"
description:
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Awards & Honors
- 2024-2026	Junior Research Fellowship (£10K), Wolfson College, University of Oxford
- 2024-2025	Wellcome Centre for Integrative Neuroimaging Seed Grant (£15K), University of Oxford
- 2023-2025	Marie Skłodowska-Curie Postdoctoral Fellowship (€221K), Horizon Europe
- 2019-2022	Undergraduate Research Grant Recipient Advisor (3 times), UC Irvine ($2,400)
- 2022 AGS Recovery Fellowship, Associated Graduate Students, UC Irvine ($1,000)
- 2022 Spring Conference Grant Award, Associated Graduate Students, UC Irvine ($250)
- 2021 Grant Writing Fellowship, School of Social Sciences, UC Irvine ($7,000)
- 2021 Cascade Mentoring Fellow, Graduate Division, UC Irvine ($6,000)
- 2021 Jean-Claude Falmagne Research Award, UC Irvine ($3,000)
- 2021 Renée Harwick Advanced Graduate Student Award, UC Irvine ($1,000)
- 2021 Outstanding Scholarship Award, School of Social Sciences, UC Irvine ($250)
- 2021 Virtual Conference Grant Award, Associated Graduate Students, UC Irvine ($250)
- 2021 Grad Slam Semi-Finalist, Graduate Division, UC Irvine (Honorary)
- 2020 DTEI Graduate Fellow, Division of Teaching Excellence and Innovation, UC Irvine ($5,000)
- 2017 NVIDIA GPU Grant, NVIDIA Corporation ($2,000)
- 2017-2019	Government Scholarship to Study Abroad, Ministry of Education, Taiwan ($32,000)
- 2017 Honorary member of the Phi Tau Phi Scholastic Honor Society (Honorary)
- 2017 Outstanding Graduating Award (1st Class Honor), National Chengchi University, Taiwan
- 2014-2017	Student of Honor Presidential Award (6 times), National Chengchi University, Taiwan ($1,000)
- 2015 Outstanding Undergraduate Student Award, Lung Shan Temple, Taiwan ($350)
- 2015 Dr. Fa-Mi Chen Memorial Scholarship, Taiwan ($100)