---
title: "Posters/ Peer-reviewed Abstracts"
description: 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**POSTERS AT SCIENTIFIC CONFERENCES**

**Pin-Chun Chen** and Bernhard Staresina (2024, Oct) Simultaneous EEG-MEG sleep recording and source localization reveal precise spatial temporal distribution of spindle activity during sleep. MEG-UKI Conference, Birmingham, UK

**Pin-Chun Chen**, Jing Zhang, Arielle Tambini, Sara C. Mednick (2022, June) How do Slow Oscillation and and Vagal Activity Support Working Memory? An EEG/fMRI Study. Poster presented at the 35th Annual Meeting of the American Associated Professional Sleep Societies, Charlotte, NC, USA

**Pin-Chun Chen**, Lauren N. Whitehurst, Hamid Niknazar, William A Alaynick, Lauren N. Whitehurst, and Sara C. Mednick (2021, Aug) Competitive dynamics underlie cognitive improvements during sleep. Poster presented at the 41st Annual Conference of North America Taiwanese Professors’ Association (Virtual)

**Pin-Chun Chen**, Lauren N. Whitehurst, Hamid Niknazar, William A Alaynick, Lauren N. Whitehurst, and Sara C. Mednick (2021, April) The sleeping brain switches between working memory and long- term memory processing. Poster presented at the Women in STEM Symposium 2021 (Virtual)

**Pin-Chun Chen**, Lauren N. Whitehurst, Mohsen Naji, and Sara C. Mednick (2020, Aug) Age-related changes in central autonomic couplings during sleep. Poster presented at the 34th Annual Meeting of the American Associated Professional Sleep Societies (Virtual)

**Pin-Chun Chen**, Lauren N. Whitehurst, Mohsen Naji, and Sara C. Mednick (2019, Sep) Coupling of Autonomic and Central events during Sleep Boosts Working Memory in Healthy Young Adults. Poster presented at the Annual Meeting of the World Sleep Congress, Vancouver, BC, Canada

**Pin-Chun Chen**, Negin Sattari, Lauren N. Whitehurst, and Sara C. Mednick (2019, June) Parasympathetic Activity during Sleep, but not Wake, Facilitates Working Memory Improvement: A Comparison of Young and Older Adults. Poster presented at the Annual Meeting of the World Sleep Congress, Vancouver, BC, Canada

**Pin-Chun Chen**, Lauren N. Whitehurst, Mohsen Naji, and Sara C. Mednick (2019, June) Coupling of Autonomic and Central events during Sleep Boosts Working Memory in Healthy Young Adults. Poster presented at the Annual Meeting of the American Associated Professional Sleep Societies, San Antonio, TX, USA

**Pin-Chun Chen**, Lauren N. Whitehurst, Mohsen Naji, and Sara C. Mednick (2018, April) A Daytime Nap Facilitates Working Memory in Healthy Young Adults. Poster presented at the Learning & Memory 2018, Huntington Beach, CA, USA

**Pin-Chun Chen**, Ya-Wen Jan, and Chien-Ming Yang (2016, June). Discrepancy between Subjective and Objective Actigraphic Sleep Estimation for Individuals with Low and High Sleep Vulnerability. Poster presented at the Annual Meeting of the American Associated Professional Sleep Societies, Denver, CO, USA

**MENTEE-LED POSTERS**

Alison B. Morehouse, Katharine C. Simon, Jing Zhang, **Pin-Chun Chen**, Lauren N. Whitehurst, Sara C. Mednick (2023, April) Does cardiac autonomic variation across sleep stages differentially impact emotional and neutral memory consolidation? Poster at Learning & Memory 2023, Huntington Beach, CA, USA

Alessandra Shuster, **Pin-Chun Chen**, Hamid Niknazar, Sara C. Mednick (2023, April) Identifying Novel Markers of Memory in REM Sleep. Poster at the International Conference on Learning & Memory 2023, Huntington Beach, CA, USA

Anjana Subramoniam, **Pin-Chun Chen**, Sara Mednick, Lauren N. Whitehurst (2022, June) Slow oscillation power and heart rate variability during sleep predicts next-day subjective sleepiness in healthy young adults. Poster at the 35th Annual Meeting of the American Associated Professional Sleep Societies, Charlotte, NC, USA

Ash Arumugam, Spencer Mair, Jing Zhang, **Pin-Chun Chen** (2022, May) Role of Sex Hormones and Sleep on Anxiety Levels. Poster at the 2022 UCLA Psychology Undergraduate Research Conference (PURC).

Shreya Cho, Kevin Sam, Jing Zhang, **Pin-Chun Chen** (2022, May) The Interaction Between Dream Recall, Declarative Memory, and Sex Hormones. Poster at the 2022 UCLA Psychology Undergraduate Research Conference (PURC).

Cassandra Delvey and **Pin-Chun Chen** (2018, Nov) Central Autonomic Couplings During Sleep Can Predict Sleep-Induced Working Memory Improvement. Poster at the 2018 Southern California Conferences for Undergraduate Research.

Mathew Bayati and **Pin-Chun Chen** (2018, Nov) Age Related Changes in Central Autonomic Couplings During Sleep. Poster at the 2018 Southern California Conferences for Undergraduate Research.
